apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ittalent-mysql-replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: gaellopes/banco-it-talent:v1
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "mydatabase"
          ports:
            - containerPort: 3306
